name: di-cho-tien-loi-backend
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.11
  
  # Main dependencies
  - fastapi>=0.110.0
  - uvicorn>=0.29.0
  - sqlalchemy>=2.0.0
  - alembic>=1.13.0
  - pydantic-settings>=2.2.0
  - pyjwt>=2.8.0
  - bcrypt>=4.1.2
  - email-validator>=2.1.0
  - psycopg2>=2.9.9
  - redis-py>=5.0.3
  - celery>=5.3.6
  - boto3>=1.34.0
  - minio>=7.2.7
  - httpx>=0.27.0
  
  # Development dependencies
  - pytest>=8.1.0
  - pytest-asyncio>=0.23.0
  - ruff>=0.3.0
  - black>=24.2.0
  - mypy>=1.8.0
  
  # Additional useful packages for development
  - pip
  - jupyter
  - ipython
  
  # Use pip for packages not available in conda
  - pip:
    - uvicorn[standard]>=0.29.0
    - factory-boy>=3.3.0