"""Update food models

Revision ID: 07d18eb740e3
Revises: a88727c026d7
Create Date: 2025-11-12 10:36:45.000843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d18eb740e3'
down_revision = 'a88727c026d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('categories_created_by_fkey'), 'categories', type_='foreignkey')
    op.drop_constraint(op.f('categories_group_id_fkey'), 'categories', type_='foreignkey')
    op.drop_column('categories', 'created_by')
    op.drop_column('categories', 'group_id')
    op.drop_column('categories', 'sort_order')
    op.drop_column('categories', 'is_active')
    op.drop_column('categories', 'icon')
    op.drop_column('categories', 'color')
    op.drop_constraint(op.f('units_group_id_fkey'), 'units', type_='foreignkey')
    op.drop_column('units', 'group_id')
    op.drop_column('units', 'symbol')
    op.drop_column('units', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('units', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('units', sa.Column('symbol', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('units', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('units_group_id_fkey'), 'units', 'groups', ['group_id'], ['id'])
    op.add_column('categories', sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('categories', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('categories_group_id_fkey'), 'categories', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(op.f('categories_created_by_fkey'), 'categories', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###