"""create recipes table

Revision ID: 26a9a495ec51
Revises: af3e88aedcc0
Create Date: 2025-12-08 17:43:10.540799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a9a495ec51'
down_revision = 'af3e88aedcc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###