"""Add API spec user fields

Revision ID: a88727c026d7
Revises: e3e0e9e26f90
Create Date: 2025-11-10 07:31:22.534489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88727c026d7'
down_revision = 'e3e0e9e26f90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('type', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('country_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('is_activated', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('belongs_to_group_admin_id', sa.Integer(), nullable=False))
    op.alter_column('users', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'timezone',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'belongs_to_group_admin_id')
    op.drop_column('users', 'device_id')
    op.drop_column('users', 'is_activated')
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'country_code')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'type')
    # ### end Alembic commands ###