"""create meal plans table

Revision ID: af3e88aedcc0
Revises: 28effbada5ff
Create Date: 2025-12-08 17:41:39.319473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af3e88aedcc0'
down_revision = '28effbada5ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###