# Base schemas
from .base import (
    BaseResponse,
    ResultMessage,
    UserData,
)

# Authentication schemas
from .auth import (
    LoginRequest,
    LoginResponse,
    LogoutRequest,
    LogoutResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    RegisterRequest,
    RegisterResponse,
    SendVerificationCodeRequest,
    SendVerificationCodeResponse,
    VerifyEmailRequest,
    VerifyEmailResponse,
)

# User schemas
from .user import (
    AddMemberRequest,
    AddMemberResponse,
    ChangePasswordRequest,
    ChangePasswordResponse,
    CreateGroupRequest,
    CreateGroupResponse,
    DeleteMemberRequest,
    DeleteMemberResponse,
    DeleteUserRequest,
    DeleteUserResponse,
    EditUserRequest,
    EditUserResponse,
    GetGroupMembersRequest,
    GetGroupMembersResponse,
    GetUserRequest,
    GetUserResponse,
    GroupMemberData,
    SaveNotificationTokenRequest,
    SaveNotificationTokenResponse,
    UserResponse,
)

# Export all for * imports
__all__ = [
    # Base
    "ResultMessage",
    "BaseResponse",
    # User Auth
    "UserData",
    "LoginRequest",
    "LoginResponse",
    "RegisterRequest",
    "RegisterResponse",
    "LogoutRequest",
    "LogoutResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "SendVerificationCodeRequest",
    "SendVerificationCodeResponse",
    "VerifyEmailRequest",
    "VerifyEmailResponse",
    # User Edit
    "ChangePasswordRequest",
    "ChangePasswordResponse",
    "EditUserRequest",
    "EditUserResponse",
    "SaveNotificationTokenRequest",
    "SaveNotificationTokenResponse",
    # User Group
    "GroupMemberData",
    "CreateGroupRequest",
    "CreateGroupResponse",
    "AddMemberRequest",
    "AddMemberResponse",
    "DeleteMemberRequest",
    "DeleteMemberResponse",
    "GetGroupMembersRequest",
    "GetGroupMembersResponse",
    # User
    "GetUserRequest",
    "GetUserResponse",
    "DeleteUserRequest",
    "DeleteUserResponse",
    "UserResponse",
    # Admin
    "LogData",
    "GetLogsRequest",
    "GetLogsResponse",
    # Admin Category
    "CategoryData",
    "AddCategoryRequest",
    "AddCategoryResponse",
    "GetAllCategoriesRequest",
    "GetAllCategoriesResponse",
    "EditCategoryRequest",
    "EditCategoryResponse",
    "DeleteCategoryRequest",
    "DeleteCategoryResponse",
    # Admin Unit
    "UnitData",
    "CreateUnitRequest",
    "CreateUnitResponse",
    "GetAllUnitsRequest",
    "GetAllUnitsResponse",
    "EditUnitRequest",
    "EditUnitResponse",
    "DeleteUnitRequest",
    "DeleteUnitResponse",
    # Food
    "UnitOfMeasurementData",
    "FoodCategoryData",
    "FoodData",
    "CreateFoodRequest",
    "CreateFoodResponse",
    "UpdateFoodRequest",
    "UpdateFoodResponse",
    "DeleteFoodRequest",
    "DeleteFoodResponse",
    "GetAllFoodsRequest",
    "GetAllFoodsResponse",
    "GetUnitsRequest",
    "GetUnitsResponse",
    "GetCategoriesRequest",
    "GetCategoriesResponse",
    # Fridge
    "FridgeItemData",
    "CreateFridgeItemRequest",
    "CreateFridgeItemResponse",
    "UpdateFridgeItemRequest",
    "UpdateFridgeItemResponse",
    "DeleteFridgeItemRequest",
    "DeleteFridgeItemResponse",
    "GetAllFridgeItemsRequest",
    "GetAllFridgeItemsResponse",
    "GetSpecificFridgeItemRequest",
    "GetSpecificFridgeItemResponse",
    # Shopping List
    "ShoppingListData",
    "TaskData",
    "ShoppingListWithTasks",
    "CreateShoppingListRequest",
    "CreateShoppingListResponse",
    "UpdateShoppingListRequest",
    "UpdateShoppingListResponse",
    "DeleteShoppingListRequest",
    "DeleteShoppingListResponse",
    "CreateTasksRequest",
    "CreateTasksResponse",
    "GetShoppingTasksRequest",
    "GetShoppingTasksResponse",
    "DeleteTaskRequest",
    "DeleteTaskResponse",
    "UpdateTaskRequest",
    "UpdateTaskResponse",
    "MarkTaskRequest",
    "MarkTaskResponse",
    # Meal Plan
    "MealPlanFoodData",
    "MealPlanData",
    "CreateMealPlanRequest",
    "CreateMealPlanResponse",
    "DeleteMealPlanRequest",
    "DeleteMealPlanResponse",
    "UpdateMealPlanRequest",
    "UpdateMealPlanResponse",
    "GetMealPlansByDateRequest",
    "GetMealPlansByDateResponse",
    # Recipe
    "RecipeFoodData",
    "RecipeData",
    "CreateRecipeRequest",
    "CreateRecipeResponse",
    "UpdateRecipeRequest",
    "UpdateRecipeResponse",
    "DeleteRecipeRequest",
    "DeleteRecipeResponse",
    "GetRecipesByFoodIdRequest",
    "GetRecipesByFoodIdResponse",
]
